# Generated by Django 2.0.1 on 2018-01-25 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
