# Generated by Django 2.0.1 on 2018-01-29 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my', '0006_auto_20180128_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='users',
        ),
        migrations.AddField(
            model_name='rooms',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
